name: mohammadi mahdi mohammadi 01131147907026

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger on

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request
        run: curl -X POST https://shams.sython.ir/test.php/?name=MohammadMahdiMohmmadi&cod=01131147907026
